// Run in an isolated touch-enabled Playwright context; checks animate real UI actions.
async page => {
  const assert=(ok,message)=>{if(!ok)throw Error(message)};
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const base='http://127.0.0.1:4173/';
  await page.route('https://www.gstatic.com/firebasejs/**',route=>route.abort());
  await page.route(base,async route=>{
    const response=await route.fetch();
    await route.fulfill({response,body:(await response.text()).replace('</script></body>',
      'window.check={act,render,feedback,get S(){return S},get W(){return W},set FB(value){FB=value}};</script></body>')});
  });
  await page.addInitScript(()=>localStorage.lift20_seen=1);
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:393,height:852});
  await page.goto(base);
  await page.waitForFunction(()=>window.check);
  const nav=async view=>page.locator(`nav [data-v="${view}"]`).click();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.page-head')).opacity==='1');
  assert(await page.locator('.summary-tile').first().evaluate(el=>el.classList.contains('revealed')),'Visible cards reveal');
  await page.locator('.stats-strip').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.stats-strip')).opacity==='1');
  assert(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollbarWidth==='thin'&&getComputedStyle(document.documentElement).scrollbarColor!=='auto'),'Thin, styled native scrollbar');
  await page.evaluate(()=>{
    const now=Date.now();check.S.w=Array.from({length:40},(_,i)=>({d:now-(39-i)*86400000,kg:63-i/10}));check.S.pr.dip=6;
  });
  await nav('stats');
  assert(await page.evaluate(()=>document.querySelector('nav').style.getPropertyValue('--nav-index')==='3'),'Navigation indicator follows selected tab');
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.weight-card')).opacity==='1');
  const before=await page.locator('#wi').inputValue();
  const up=page.locator('[data-a=wstep][data-v="0.1"]'),box=await up.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
  await page.mouse.down();
  assert(await up.locator('.tap-wave').count()===1,'Tap wave appears at pointer contact');
  await page.mouse.up();
  assert(Number(await page.locator('#wi').inputValue())===Math.round((Number(before)+.1)*10)/10,'Feedback does not delay weight step');
  assert(await page.locator('#wi').evaluate(el=>el.getAnimations().length>0),'Value change feedback runs');
  await page.waitForFunction(()=>!document.querySelector('.tap-wave'));
  await page.locator('#wi').fill('0');
  await page.locator('[data-a=logw]').click();
  assert(await page.locator('#wi').getAttribute('aria-invalid')==='true','Invalid input has accessible error state');
  assert(await page.evaluate(()=>check.S.w.length===40),'Invalid weight does not save');
  await page.locator('#wi').fill('62.5');
  assert(await page.locator('#wi').getAttribute('aria-invalid')===null,'Editing clears stale error state');
  await page.locator('[data-a=logw]').click();
  assert(await page.evaluate(()=>check.S.w.at(-1).kg===62.5),'Weight saves immediately');
  assert(await page.locator('.weight-card').evaluate(el=>el.getAnimations().length>0),'Successful save feedback runs');
  await page.locator('.weight-history summary').click();
  await page.waitForFunction(()=>document.querySelector('.weight-history').open&&document.querySelector('.weight-entries').clientHeight>0);
  assert(await page.locator('.weight-entries .wl').count()===40,'Animated history preserves every entry');
  await page.locator('.weight-entries').evaluate(el=>el.scrollTop=100);
  assert(await page.locator('.weight-entries').evaluate(el=>el.scrollTop>0),'Styled history scrollbar remains scrollable');
  await page.locator('.weight-history summary').focus();
  await page.keyboard.press('Enter');
  assert(!await page.locator('.weight-history').evaluate(el=>el.open),'Animated history remains keyboard accessible');
  await page.waitForFunction(()=>!document.querySelector('.toast'));
  await nav('ex');
  await page.locator('.chip[data-v=legs]').click();
  assert(await page.locator('.chip[data-v=legs]').getAttribute('aria-pressed')==='true','Animated filters retain selected state');
  await page.locator('#search').fill('goblet');
  assert(await page.locator('.exercise-card').count()===1,'Animated search results');
  assert(await page.locator('#search').evaluate(el=>el===document.activeElement&&el.selectionStart===6),'Search keeps focus and caret');
  await page.locator('#search').evaluate(el=>el.blur());
  await page.locator('.exercise-card .lnk').click();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('#dlg')).opacity==='1');
  await page.locator('#dlg [data-a=play]').click();
  assert(await page.locator('#dlg iframe').count()===1,'Animated dialog still loads video');
  await page.keyboard.press('Escape');
  assert(!await page.locator('#dlg').evaluate(el=>el.open),'Escape releases modal immediately');
  await page.waitForFunction(()=>!document.querySelector('#dlg iframe'));
  await page.locator('#dlg').waitFor({state:'hidden'});
  await nav('prog');
  await page.evaluate(()=>{check.S.prog.X=['dip'];check.render(1)});
  await page.locator('[data-a=start][data-v=X]').click();
  await page.locator('#w [data-a=vp]').click();
  await page.locator('#wv [data-a=play]').click();
  await page.evaluate(()=>window.motionFrame=document.querySelector('#wv iframe'));
  await page.locator('#w [data-a=rep][data-v="1"]').click();
  assert(await page.locator('#rv').textContent()==='7','Animated rep step saves immediately');
  await page.locator('#cs').click();
  assert(await page.locator('#cs').textContent()==='New personal best!','Personal best feedback');
  await page.waitForSelector('#rt');
  await page.locator('[data-a=rp]').click();
  assert(await page.locator('.ring').evaluate(el=>el.classList.contains('paused')),'Pause feedback matches timer state');
  const paused=await page.locator('#rt').textContent();
  await page.locator('[data-a=rt][data-v="15"]').click();
  await page.locator('[data-a=rt][data-v="-15"]').click();
  assert(await page.locator('#rt').textContent()===paused,'Animated timer adjustments preserve time');
  await page.locator('[data-a=rp]').click();
  await page.evaluate(()=>check.W.rest.end=Date.now()-1000);
  await page.waitForFunction(()=>document.querySelector('.ring').classList.contains('dn'));
  assert(await page.locator('#nx').textContent()==='Next set','Rest completion feedback');
  await page.locator('#nx').click();
  assert(await page.evaluate(()=>window.motionFrame===document.querySelector('#wv iframe')),'Active iframe survives animated set/rest changes');
  for(let i=0;i<2;i++){
    await page.locator('#cs').click();
    await page.waitForFunction(()=>!check.W.busy);
    if(await page.locator('#nx').count())await page.locator('#nx').click();
  }
  assert(await page.locator('#w h1').textContent()==='Workout complete','Animated workout completion');
  assert(await page.locator('.cf').count()===26,'Workout celebration appears');
  assert(await page.evaluate(()=>check.S.hist.at(-1).logs.length===3),'Animation preserves all sets');
  await page.waitForFunction(()=>[...document.querySelectorAll('#w .n')].map(el=>el.textContent).join(',')==='1,3,21');
  await page.waitForFunction(()=>[...document.querySelectorAll('#w .card')].every(el=>getComputedStyle(el).opacity==='1'));
  assert(await page.locator('#w .grid .card').evaluateAll(cards=>cards.every(el=>el.offsetTop===cards[0].offsetTop)),'Summary cards stay aligned');
  await page.screenshot({path:'output/playwright/motion-complete-iphone.png',animations:'disabled'});
  await page.locator('#w [data-a=close]').click();
  await page.waitForFunction(()=>document.activeElement.closest('nav'));
  await nav('me');
  // Mock only the pending/error UI; this is not a Google authentication test.
  await page.evaluate(()=>{window.signInCalls=0;check.FB={auth:{currentUser:null},GoogleAuthProvider:class{},signInWithPopup:()=>{window.signInCalls++;return new Promise((_,reject)=>window.rejectSignIn=reject)}}});
  const signin=page.locator('#app [data-a=signin]');
  await signin.click();
  assert(await signin.isDisabled()&&await signin.getAttribute('aria-busy')==='true','Sign-in busy feedback');
  await page.evaluate(()=>check.act.signin('',document.querySelector('#app [data-a=signin]')));
  await page.waitForFunction(()=>window.signInCalls===1);
  await page.evaluate(()=>window.rejectSignIn(Error('Test-only cancellation')));
  await page.waitForFunction(()=>!document.querySelector('#app [data-a=signin]').disabled);
  assert(await signin.getAttribute('aria-busy')===null,'Failed sign-in restores button');
  await page.evaluate(()=>check.FB=null);
  await page.waitForFunction(()=>!document.querySelector('.toast'));
  await page.evaluate(()=>{for(const view of ['home','ex','stats','prog','home'])check.act.nav(view)});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>[...document.querySelectorAll('.reveal')].every(el=>getComputedStyle(el).opacity==='1'));
  await page.waitForFunction(()=>document.getAnimations().length===0);
  assert(await page.evaluate(()=>document.getAnimations().length===0),'Live reduced-motion change cancels animations and reveals content');
  await nav('stats');
  await page.locator('[data-a=wstep][data-v="0.1"]').click();
  assert(await page.locator('.tap-wave').count()===0&&await page.evaluate(()=>document.getAnimations().length===0),'Reduced motion skips tap/value animations');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await nav('home');
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.summary-tile')).opacity==='1');
  await page.setViewportSize({width:820,height:1180});
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.stats-strip')).opacity==='1');
  await page.screenshot({path:'output/playwright/motion-home-ipad.png',animations:'disabled'});
  assert(errors.length===0,'No runtime errors: '+errors.join('; '));
  return 'PASS: taps/cleanup; navigation/reveals; scrollbar; weight/error/success/history; filter/search; dialog/video; reps/PR/rest; iframe continuity; celebration; pending sign-in UI; rapid navigation; live reduced motion.';
}
